# This is a Read the Docs configuration file for Sphinx projects.
# References: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

# Indicate which OS and Python version we want Read the Docs to use
# when compiling our documentation.
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # Override parts of the standard Read the Docs build process.
  # Reference: https://docs.readthedocs.io/en/stable/build-customization.html
  jobs:
    pre_build:
      - python compose.py && cd docs && make html

# Tell Sphinx where our `conf.py` file resides.
sphinx:
  configuration: docs/conf.py

# Tell Sphinx where our Python package requirements list resides.
python:
  install:
    - requirements: requirements.txt
